---
watch:
  - .trmnlp.yml
  - src
custom_fields:
  person: mitch_mcconnell
  tone: pitch_black
transform_runtime: enabled
variables:
  trmnl:
    plugin_settings:
      instance_name: Is He Dead Yet?
